version: '3.8'
services:
  mysql:
    image: mysql:5.7
    ports:
      - '33060:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: covidal
      MYSQL_ROOT_PASSWORD: covid4l
